//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionPackager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolutionPackager.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to import solution?.
        /// </summary>
        public static string Confirm_Import {
            get {
                return ResourceManager.GetString("Confirm_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to import &amp; publish solution?.
        /// </summary>
        public static string Confirm_ImportAndPublish {
            get {
                return ResourceManager.GetString("Confirm_ImportAndPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok to import?.
        /// </summary>
        public static string Confirm_Title_OkToImport {
            get {
                return ResourceManager.GetString("Confirm_Title_OkToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set working directory.
        /// </summary>
        public static string ErrorMessage_CouldNotSetWorkingDirectory {
            get {
                return ResourceManager.GetString("ErrorMessage_CouldNotSetWorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding solution file to project.
        /// </summary>
        public static string ErrorMessage_ErrorAddingSolutionFileProject {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorAddingSolutionFileProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating command arguments.
        /// </summary>
        public static string ErrorMessage_ErrorCreatingCommandArguments {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorCreatingCommandArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating temporary directory to extract files.
        /// </summary>
        public static string ErrorMessage_ErrorCreatingTemp {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorCreatingTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting file name from temp path.
        /// </summary>
        public static string ErrorMessage_ErrorGettingFileNameFromTemp {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorGettingFileNameFromTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error importing solution.
        /// </summary>
        public static string ErrorMessage_ErrorImportingSolution {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorImportingSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving solution.
        /// </summary>
        public static string ErrorMessage_ErrorRetrievingSolution {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorRetrievingSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving solutions.
        /// </summary>
        public static string ErrorMessage_ErrorRetrievingSolutions {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorRetrievingSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing solution to temporary directory.
        /// </summary>
        public static string ErrorMessage_ErrorWritingTemp {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorWritingTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Solution.xml: invalid version.
        /// </summary>
        public static string ErrorMessage_InvalidSolutionXml_InvalidVersion {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidSolutionXml_InvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Solution.xml: could not locate &apos;Versions&apos; node.
        /// </summary>
        public static string ErrorMessage_InvalidSolutionXml_VersionsNode {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidSolutionXml_VersionsNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set the Solution Packager path in options.
        /// </summary>
        public static string ErrorMessage_SetSolutionPackagerPath {
            get {
                return ResourceManager.GetString("ErrorMessage_SetSolutionPackagerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error setting Solution.xml version.
        /// </summary>
        public static string ErrorMessage_SetSolutionXmlVersion {
            get {
                return ResourceManager.GetString("ErrorMessage_SetSolutionXmlVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolutionPackager.exe not found.
        /// </summary>
        public static string ErrorMessage_SolutionPackagerNotFound {
            get {
                return ResourceManager.GetString("ErrorMessage_SolutionPackagerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.xml does not exist.
        /// </summary>
        public static string ErrorMessage_SolutionXmlNotExist {
            get {
                return ResourceManager.GetString("ErrorMessage_SolutionXmlNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error setting Solution.xml version: new version cannot be lower than old version.
        /// </summary>
        public static string ErrorMessage_SolutionXmlVersionTooLow {
            get {
                return ResourceManager.GetString("ErrorMessage_SolutionXmlVersionTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error validating Solution.xml.
        /// </summary>
        public static string ErrorMessage_UnexpectedErrorValidatingSolutionXml {
            get {
                return ResourceManager.GetString("ErrorMessage_UnexpectedErrorValidatingSolutionXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string Message_Begin {
            get {
                return ResourceManager.GetString("Message_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting and getting unmanaged solution.
        /// </summary>
        public static string Message_ConnectingGettingUnmanaegedSolution {
            get {
                return ResourceManager.GetString("Message_ConnectingGettingUnmanaegedSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string Message_End {
            get {
                return ResourceManager.GetString("Message_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing Solution Packager command.
        /// </summary>
        public static string Message_ErrorExecutingSolutionPackager {
            get {
                return ResourceManager.GetString("Message_ErrorExecutingSolutionPackager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting solution.
        /// </summary>
        public static string Message_ExtractingSolution {
            get {
                return ResourceManager.GetString("Message_ExtractingSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing solution.
        /// </summary>
        public static string Message_ImportingSolution {
            get {
                return ResourceManager.GetString("Message_ImportingSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging solution.
        /// </summary>
        public static string Message_PackagingSolution {
            get {
                return ResourceManager.GetString("Message_PackagingSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing customizations.
        /// </summary>
        public static string Message_PublishingCustomizations {
            get {
                return ResourceManager.GetString("Message_PublishingCustomizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieved solution.
        /// </summary>
        public static string Message_RetrievedSolution {
            get {
                return ResourceManager.GetString("Message_RetrievedSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieved solutions.
        /// </summary>
        public static string Message_RetrievedSolutions {
            get {
                return ResourceManager.GetString("Message_RetrievedSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving solutions.
        /// </summary>
        public static string Message_RetrievingSolutions {
            get {
                return ResourceManager.GetString("Message_RetrievingSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout executing Solution Packager command.
        /// </summary>
        public static string Message_TimoutExecutingSolutionPackager {
            get {
                return ResourceManager.GetString("Message_TimoutExecutingSolutionPackager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Message_Updated {
            get {
                return ResourceManager.GetString("Message_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        public static string Message_Updating {
            get {
                return ResourceManager.GetString("Message_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error extracting solution.
        /// </summary>
        public static string MessageBox_ErrorExtractingSolution {
            get {
                return ResourceManager.GetString("MessageBox_ErrorExtractingSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error importing or publishing solution.
        /// </summary>
        public static string MessageBox_ErrorImportingOrPublishing {
            get {
                return ResourceManager.GetString("MessageBox_ErrorImportingOrPublishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error packaging solution.
        /// </summary>
        public static string MessageBox_ErrorPackagingSolution {
            get {
                return ResourceManager.GetString("MessageBox_ErrorPackagingSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving solutions.
        /// </summary>
        public static string MessageBox_ErrorRetrievingSolutions {
            get {
                return ResourceManager.GetString("MessageBox_ErrorRetrievingSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating Solution.xml version.
        /// </summary>
        public static string MessageBox_ErrorUpdatingSolutionXmlVersion {
            get {
                return ResourceManager.GetString("MessageBox_ErrorUpdatingSolutionXmlVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Solution.xml version number.
        /// </summary>
        public static string MessageBox_InvalidSolutionXmlVersion {
            get {
                return ResourceManager.GetString("MessageBox_InvalidSolutionXmlVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid version number.
        /// </summary>
        public static string MessageBox_InvalidVersionNumber {
            get {
                return ResourceManager.GetString("MessageBox_InvalidVersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find solution.
        /// </summary>
        public static string MessageBox_UnableToFindSolution {
            get {
                return ResourceManager.GetString("MessageBox_UnableToFindSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution To Package.
        /// </summary>
        public static string SolutionList_ComboBox_ToolTip {
            get {
                return ResourceManager.GetString("SolutionList_ComboBox_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Solution Packager Log?.
        /// </summary>
        public static string SolutionPackager_EnableSolutionPackagerLogLabel_Label_Content {
            get {
                return ResourceManager.GetString("SolutionPackager_EnableSolutionPackagerLogLabel_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Options.
        /// </summary>
        public static string SolutionPackager_ExtractOptionsLabel_Label_Content {
            get {
                return ResourceManager.GetString("SolutionPackager_ExtractOptionsLabel_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Options.
        /// </summary>
        public static string SolutionPackager_ImportOptionsLabel_Label_Content {
            get {
                return ResourceManager.GetString("SolutionPackager_ImportOptionsLabel_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string SolutionPackager_ImportSolution_Button_Content {
            get {
                return ResourceManager.GetString("SolutionPackager_ImportSolution_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Solution.
        /// </summary>
        public static string SolutionPackager_ImportSolution_Button_ToolTip {
            get {
                return ResourceManager.GetString("SolutionPackager_ImportSolution_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Folder.
        /// </summary>
        public static string SolutionPackager_PackageFolderLabel_Label_Content {
            get {
                return ResourceManager.GetString("SolutionPackager_PackageFolderLabel_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string SolutionPackager_PackageSolution_Button_Content {
            get {
                return ResourceManager.GetString("SolutionPackager_PackageSolution_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Solution.
        /// </summary>
        public static string SolutionPackager_PackageSolution_Button_ToolTip {
            get {
                return ResourceManager.GetString("SolutionPackager_PackageSolution_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Type.
        /// </summary>
        public static string SolutionPackager_PackageTypeLabel_Label_Content {
            get {
                return ResourceManager.GetString("SolutionPackager_PackageTypeLabel_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack Options.
        /// </summary>
        public static string SolutionPackager_PackOptionsLabel_Label_Content {
            get {
                return ResourceManager.GetString("SolutionPackager_PackOptionsLabel_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish All?.
        /// </summary>
        public static string SolutionPackager_PublishAllLabel_Label_Content {
            get {
                return ResourceManager.GetString("SolutionPackager_PublishAllLabel_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Solution Files?.
        /// </summary>
        public static string SolutionPackager_SaveSolutionsLabel_Label_Content {
            get {
                return ResourceManager.GetString("SolutionPackager_SaveSolutionsLabel_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Folder.
        /// </summary>
        public static string SolutionPackager_SolutionFolderLabe_Label_Content {
            get {
                return ResourceManager.GetString("SolutionPackager_SolutionFolderLabe_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Name.
        /// </summary>
        public static string SolutionPackager_SolutionNameLabel_Label_Content {
            get {
                return ResourceManager.GetString("SolutionPackager_SolutionNameLabel_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solutions.
        /// </summary>
        public static string SolutionPackager_SolutionsLabel_Label_Content {
            get {
                return ResourceManager.GetString("SolutionPackager_SolutionsLabel_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpackage.
        /// </summary>
        public static string SolutionPackager_UnpackageSolution_Button_Content {
            get {
                return ResourceManager.GetString("SolutionPackager_UnpackageSolution_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpackage Solution.
        /// </summary>
        public static string SolutionPackager_UnpackageSolution_Button_ToolTip {
            get {
                return ResourceManager.GetString("SolutionPackager_UnpackageSolution_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the version number in the local project&apos;s Solution.xml.
        /// </summary>
        public static string SolutionPackager_UpdateVersionImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("SolutionPackager_UpdateVersionImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Map File?.
        /// </summary>
        public static string SolutionPackager_UseMapFileLabel_Label_Content {
            get {
                return ResourceManager.GetString("SolutionPackager_UseMapFileLabel_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crm DevEx: Solution Packager.
        /// </summary>
        public static string SolutionPackager_Window_Title {
            get {
                return ResourceManager.GetString("SolutionPackager_Window_Title", resourceCulture);
            }
        }
    }
}
