// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------

using System;

namespace CrmDeveloperExtensions2
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GuidCrmDeveloperExtensionsPkgString = "a4fa8f78-98af-4633-8621-bbdd7792a6ac";
        public const string GuidCrmDevExCmdSetString = "95cd7b0b-0592-4683-b42c-a79a41380ffe";
        public static Guid GuidCrmDeveloperExtensionsPkg = new Guid(GuidCrmDeveloperExtensionsPkgString);
        public static Guid GuidCrmDevExCmdSet = new Guid(GuidCrmDevExCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ProjectMenuGroup = 0x1020;
        public const int CmdidWebResourceDeployerWindow = 0x0102;
        public const int TopLevelMenu = 0x0100;
        public const int TopLevelMenuGroup = 0x0200;
    }
}
