//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebResourceDeployer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebResourceDeployer.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new_.
        /// </summary>
        public static string DefaultPrefix {
            get {
                return ResourceManager.GetString("DefaultPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding web resource to solution.
        /// </summary>
        public static string ErrorMessage_ErrorAddingWebResourceSolution {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorAddingWebResourceSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating web resource.
        /// </summary>
        public static string ErrorMessage_ErrorCreatingWebResource {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorCreatingWebResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting web resource.
        /// </summary>
        public static string ErrorMessage_ErrorDeletingWebResource {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorDeletingWebResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving solutions.
        /// </summary>
        public static string ErrorMessage_ErrorRetrievingSolutions {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorRetrievingSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving web resource.
        /// </summary>
        public static string ErrorMessage_ErrorRetrievingWebResource {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorRetrievingWebResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving web resource content.
        /// </summary>
        public static string ErrorMessage_ErrorRetrievingWebResourceContent {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorRetrievingWebResourceContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving web resource description.
        /// </summary>
        public static string ErrorMessage_ErrorRetrievingWebResourceDescription {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorRetrievingWebResourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving web resources.
        /// </summary>
        public static string ErrorMessage_ErrorRetrievingWebResources {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorRetrievingWebResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating and publishing web resource(s).
        /// </summary>
        public static string ErrorMessage_ErrorUpdatingPublishingWebResources {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorUpdatingPublishingWebResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed.
        /// </summary>
        public static string Managed {
            get {
                return ResourceManager.GetString("Managed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string Message_AreYouSure {
            get {
                return ResourceManager.GetString("Message_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating.
        /// </summary>
        public static string Message_Creating {
            get {
                return ResourceManager.GetString("Message_Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted web resource.
        /// </summary>
        public static string Message_DeletedWebResource {
            get {
                return ResourceManager.GetString("Message_DeletedWebResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Web Resource.
        /// </summary>
        public static string Message_DeleteWebResource {
            get {
                return ResourceManager.GetString("Message_DeleteWebResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting web resource.
        /// </summary>
        public static string Message_DeletingWebResource {
            get {
                return ResourceManager.GetString("Message_DeletingWebResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will download all web resources in the current view to a matching folder structure.
        /// </summary>
        public static string Message_DownloadAllWebResources {
            get {
                return ResourceManager.GetString("Message_DownloadAllWebResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded web resource.
        /// </summary>
        public static string Message_DownloadedWebResource {
            get {
                return ResourceManager.GetString("Message_DownloadedWebResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading file.
        /// </summary>
        public static string Message_DownloadingFile {
            get {
                return ResourceManager.GetString("Message_DownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading file for compare.
        /// </summary>
        public static string Message_DownloadingFileForCompare {
            get {
                return ResourceManager.GetString("Message_DownloadingFileForCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading file(s).
        /// </summary>
        public static string Message_DownloadingFiles {
            get {
                return ResourceManager.GetString("Message_DownloadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web resource names may only include letters, numbers, periods, and nonconsecutive forward slash characters.
        /// </summary>
        public static string Message_InvalidWebResourceName {
            get {
                return ResourceManager.GetString("Message_InvalidWebResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing file.
        /// </summary>
        public static string Message_MissingFile {
            get {
                return ResourceManager.GetString("Message_MissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New web resource added to solution.
        /// </summary>
        public static string Message_NewWebResourceAddedSolution {
            get {
                return ResourceManager.GetString("Message_NewWebResourceAddedSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New web resource created.
        /// </summary>
        public static string Message_NewWebResourceCreated {
            get {
                return ResourceManager.GetString("Message_NewWebResourceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK to proceed?.
        /// </summary>
        public static string Message_OkProceed {
            get {
                return ResourceManager.GetString("Message_OkProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published web resource(s).
        /// </summary>
        public static string Message_PublishedWebResources {
            get {
                return ResourceManager.GetString("Message_PublishedWebResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieved solutions.
        /// </summary>
        public static string Message_RetrievedSolutions {
            get {
                return ResourceManager.GetString("Message_RetrievedSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieved web resource content.
        /// </summary>
        public static string Message_RetrievedWebResourceContent {
            get {
                return ResourceManager.GetString("Message_RetrievedWebResourceContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieved web resources.
        /// </summary>
        public static string Message_RetrievedWebResources {
            get {
                return ResourceManager.GetString("Message_RetrievedWebResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving solutions.
        /// </summary>
        public static string Message_RetrievingSolutions {
            get {
                return ResourceManager.GetString("Message_RetrievingSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving solutions and web resources.
        /// </summary>
        public static string Message_RetrievingSolutionsWebResources {
            get {
                return ResourceManager.GetString("Message_RetrievingSolutionsWebResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving web resources.
        /// </summary>
        public static string Message_RetrievingWebResources {
            get {
                return ResourceManager.GetString("Message_RetrievingWebResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated and published web resource(s).
        /// </summary>
        public static string Message_UpdatedPublishedWebResources {
            get {
                return ResourceManager.GetString("Message_UpdatedPublishedWebResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        public static string Message_Updating {
            get {
                return ResourceManager.GetString("Message_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating and publishing.
        /// </summary>
        public static string Message_UpdatingPublishing {
            get {
                return ResourceManager.GetString("Message_UpdatingPublishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded web resource.
        /// </summary>
        public static string Message_UploadedWebResource {
            get {
                return ResourceManager.GetString("Message_UploadedWebResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will attempt to delete the web resource.
        /// </summary>
        public static string Message_WillAttemptToDelete {
            get {
                return ResourceManager.GetString("Message_WillAttemptToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file.
        /// </summary>
        public static string MessageBox_CouldNotFindFile {
            get {
                return ResourceManager.GetString("MessageBox_CouldNotFindFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        public static string MessageBox_FileDoesNotExist {
            get {
                return ResourceManager.GetString("MessageBox_FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK to overwrite?.
        /// </summary>
        public static string MessageBox_OkOverwrite {
            get {
                return ResourceManager.GetString("MessageBox_OkOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Resource Download.
        /// </summary>
        public static string MessageBox_WebResourceDownload {
            get {
                return ResourceManager.GetString("MessageBox_WebResourceDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string NewWebResource_Cancel_Button_Content {
            get {
                return ResourceManager.GetString("NewWebResource_Cancel_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string NewWebResource_Create_Button_Content {
            get {
                return ResourceManager.GetString("NewWebResource_Create_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string NewWebResource_DescriptionLabel_Label_Content {
            get {
                return ResourceManager.GetString("NewWebResource_DescriptionLabel_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string NewWebResource_DisplayNameLabel_Label_Content {
            get {
                return ResourceManager.GetString("NewWebResource_DisplayNameLabel_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string NewWebResource_FilesLabel_Label_Content {
            get {
                return ResourceManager.GetString("NewWebResource_FilesLabel_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NewWebResource_NameLabel_Label_Content {
            get {
                return ResourceManager.GetString("NewWebResource_NameLabel_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new_.
        /// </summary>
        public static string NewWebResource_Prefix_TextBox_Text {
            get {
                return ResourceManager.GetString("NewWebResource_Prefix_TextBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        public static string NewWebResource_SolutionsLabel_Label_Content {
            get {
                return ResourceManager.GetString("NewWebResource_SolutionsLabel_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string NewWebResource_TypeLabel_Label_Content {
            get {
                return ResourceManager.GetString("NewWebResource_TypeLabel_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Web Resource.
        /// </summary>
        public static string NewWebResource_Window_Title {
            get {
                return ResourceManager.GetString("NewWebResource_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmanaged.
        /// </summary>
        public static string Unmanaged {
            get {
                return ResourceManager.GetString("Unmanaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        public static string WebResourceDeployer_AddWebResource_Button_Content {
            get {
                return ResourceManager.GetString("WebResourceDeployer_AddWebResource_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New web resource.
        /// </summary>
        public static string WebResourceDeployer_AddWebResource_Button_ToolTip {
            get {
                return ResourceManager.GetString("WebResourceDeployer_AddWebResource_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string WebResourceDeployer_CancelEditDescriptionImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("WebResourceDeployer_CancelEditDescriptionImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to map file.
        /// </summary>
        public static string WebResourceDeployer_ClickToMapLabel_TextBlock_ToolTip {
            get {
                return ResourceManager.GetString("WebResourceDeployer_ClickToMapLabel_TextBlock_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare with CRM/365.
        /// </summary>
        public static string WebResourceDeployer_CompareImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("WebResourceDeployer_CompareImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from CRM/365.
        /// </summary>
        public static string WebResourceDeployer_DeleteImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("WebResourceDeployer_DeleteImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string WebResourceDeployer_Description_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("WebResourceDeployer_Description_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string WebResourceDeployer_DisplayName_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("WebResourceDeployer_DisplayName_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download all items.
        /// </summary>
        public static string WebResourceDeployer_DownloadAllImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("WebResourceDeployer_DownloadAllImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download from CRM/365.
        /// </summary>
        public static string WebResourceDeployer_DownloadImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("WebResourceDeployer_DownloadImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit description.
        /// </summary>
        public static string WebResourceDeployer_EditDescriptionImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("WebResourceDeployer_EditDescriptionImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download: Right-click to specify folder.
        /// </summary>
        public static string WebResourceDeployer_GetWebResource_Button_ToolTip {
            get {
                return ResourceManager.GetString("WebResourceDeployer_GetWebResource_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Count.
        /// </summary>
        public static string WebResourceDeployer_ItemCount_Label_Content {
            get {
                return ResourceManager.GetString("WebResourceDeployer_ItemCount_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapped To.
        /// </summary>
        public static string WebResourceDeployer_MappedTo_DataGridTemplateColumn_Header {
            get {
                return ResourceManager.GetString("WebResourceDeployer_MappedTo_DataGridTemplateColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string WebResourceDeployer_Name_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("WebResourceDeployer_Name_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in CRM/365.
        /// </summary>
        public static string WebResourceDeployer_OpenInCrmImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("WebResourceDeployer_OpenInCrmImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string WebResourceDeployer_Publish_Button_Content {
            get {
                return ResourceManager.GetString("WebResourceDeployer_Publish_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to CRM/365.
        /// </summary>
        public static string WebResourceDeployer_Publish_Button_ToolTip {
            get {
                return ResourceManager.GetString("WebResourceDeployer_Publish_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string WebResourceDeployer_Publish_DataGridTemplateColumn_Header {
            get {
                return ResourceManager.GetString("WebResourceDeployer_Publish_DataGridTemplateColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string WebResourceDeployer_PublishItem_CheckBox_ToolTip {
            get {
                return ResourceManager.GetString("WebResourceDeployer_PublishItem_CheckBox_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save description.
        /// </summary>
        public static string WebResourceDeployer_SaveDescriptionImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("WebResourceDeployer_SaveDescriptionImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search web resources.
        /// </summary>
        public static string WebResourceDeployer_SearchText_TextBlock_Text {
            get {
                return ResourceManager.GetString("WebResourceDeployer_SearchText_TextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        public static string WebResourceDeployer_SolutionsLabel_Label_Content {
            get {
                return ResourceManager.GetString("WebResourceDeployer_SolutionsLabel_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string WebResourceDeployer_State_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("WebResourceDeployer_State_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string WebResourceDeployer_Type_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("WebResourceDeployer_Type_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo from server if you&apos;ve edited configuration file directly.
        /// </summary>
        public static string WebResourceDeployer_UndoEditDescriptionImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("WebResourceDeployer_UndoEditDescriptionImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string WebResourceDeployer_ViewDetailsImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("WebResourceDeployer_ViewDetailsImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D365 DevEx: Web Resource Deployer.
        /// </summary>
        public static string WebResourceDeployer_Window_Title {
            get {
                return ResourceManager.GetString("WebResourceDeployer_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string WebResourceTypeLabel_Label_Content {
            get {
                return ResourceManager.GetString("WebResourceTypeLabel_Label_Content", resourceCulture);
            }
        }
    }
}
