//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebResourceDeployer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebResourceDeployer.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        public static string AddWebResource_Button_Content {
            get {
                return ResourceManager.GetString("AddWebResource_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Web Resource.
        /// </summary>
        public static string AddWebResource_Button_ToolTip {
            get {
                return ResourceManager.GetString("AddWebResource_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Map File.
        /// </summary>
        public static string ClickToMapLabel_TextBlock_ToolTip {
            get {
                return ResourceManager.GetString("ClickToMapLabel_TextBlock_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare With CRM/365.
        /// </summary>
        public static string CompareImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("CompareImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete From CRM/365.
        /// </summary>
        public static string DeleteImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("DeleteImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("DisplayName_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download from CRM/365.
        /// </summary>
        public static string DownloadImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("DownloadImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download: Right-click to specify folder.
        /// </summary>
        public static string GetWebResource_Button_ToolTip {
            get {
                return ResourceManager.GetString("GetWebResource_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Count.
        /// </summary>
        public static string ItemCount_Label_Content {
            get {
                return ResourceManager.GetString("ItemCount_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapped To.
        /// </summary>
        public static string MappedTo_DataGridTemplateColumn_Header {
            get {
                return ResourceManager.GetString("MappedTo_DataGridTemplateColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("Name_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in CRM/365.
        /// </summary>
        public static string OpenInCrmImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("OpenInCrmImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish_Button_Content {
            get {
                return ResourceManager.GetString("Publish_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to CRM/365.
        /// </summary>
        public static string Publish_Button_ToolTip {
            get {
                return ResourceManager.GetString("Publish_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish_DataGridTemplateColumn_Header {
            get {
                return ResourceManager.GetString("Publish_DataGridTemplateColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string PublishItem_CheckBox_ToolTip {
            get {
                return ResourceManager.GetString("PublishItem_CheckBox_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish - Select/Unselect All.
        /// </summary>
        public static string PublishSelectAll_CheckBox_ToolTip {
            get {
                return ResourceManager.GetString("PublishSelectAll_CheckBox_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Managed.
        /// </summary>
        public static string ShowManaged_CheckBox_Content {
            get {
                return ResourceManager.GetString("ShowManaged_CheckBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        public static string SolutionsLabel_Label_Content {
            get {
                return ResourceManager.GetString("SolutionsLabel_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("State_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crm Dev: Web Resource Deployer.
        /// </summary>
        public static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("Type_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string WebResourceTypeLabel_Label_Content {
            get {
                return ResourceManager.GetString("WebResourceTypeLabel_Label_Content", resourceCulture);
            }
        }
    }
}
