//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebResourceDeployer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebResourceDeployer.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        public static string AddWebResource_Button_Content {
            get {
                return ResourceManager.GetString("AddWebResource_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Web Resource.
        /// </summary>
        public static string AddWebResource_Button_ToolTip {
            get {
                return ResourceManager.GetString("AddWebResource_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Map File.
        /// </summary>
        public static string ClickToMapLabel_TextBlock_ToolTip {
            get {
                return ResourceManager.GetString("ClickToMapLabel_TextBlock_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare With CRM/365.
        /// </summary>
        public static string CompareImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("CompareImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style Sheet (CSS).
        /// </summary>
        public static string CSS_ComboBoxItem_Content {
            get {
                return ResourceManager.GetString("CSS_ComboBoxItem_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizations.
        /// </summary>
        public static string Customizations_Button_Content {
            get {
                return ResourceManager.GetString("Customizations_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM/365 Customizations Page.
        /// </summary>
        public static string Customizations_Button_ToolTip {
            get {
                return ResourceManager.GetString("Customizations_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete From CRM/365.
        /// </summary>
        public static string DeleteImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("DeleteImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("DisplayName_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download from CRM/365.
        /// </summary>
        public static string DownloadImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("DownloadImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FilterLabel_Label_Content {
            get {
                return ResourceManager.GetString("FilterLabel_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download: Right-click to specify folder.
        /// </summary>
        public static string GetWebResource_Button_ToolTip {
            get {
                return ResourceManager.GetString("GetWebResource_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF format.
        /// </summary>
        public static string GIF_ComboBoxItem_Content {
            get {
                return ResourceManager.GetString("GIF_ComboBoxItem_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webpage (HTML).
        /// </summary>
        public static string HTML_ComboBoxItem_Content {
            get {
                return ResourceManager.GetString("HTML_ComboBoxItem_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICO format.
        /// </summary>
        public static string ICO_ComboBoxItem_Content {
            get {
                return ResourceManager.GetString("ICO_ComboBoxItem_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPG format.
        /// </summary>
        public static string JPG_ComboBoxItem_Content {
            get {
                return ResourceManager.GetString("JPG_ComboBoxItem_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script (JScript).
        /// </summary>
        public static string JS_ComboBoxItem_Content {
            get {
                return ResourceManager.GetString("JS_ComboBoxItem_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapped To.
        /// </summary>
        public static string MappedTo_DataGridTemplateColumn_Header {
            get {
                return ResourceManager.GetString("MappedTo_DataGridTemplateColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("Name_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in CRM/365.
        /// </summary>
        public static string OpenInCrmImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("OpenInCrmImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG format.
        /// </summary>
        public static string PNG_ComboBoxItem_Content {
            get {
                return ResourceManager.GetString("PNG_ComboBoxItem_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pubish.
        /// </summary>
        public static string Publish_Button_Content {
            get {
                return ResourceManager.GetString("Publish_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to CRM/365.
        /// </summary>
        public static string Publish_Button_ToolTip {
            get {
                return ResourceManager.GetString("Publish_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish_DataGridTemplateColumn_Header {
            get {
                return ResourceManager.GetString("Publish_DataGridTemplateColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string PublishItem_CheckBox_ToolTip {
            get {
                return ResourceManager.GetString("PublishItem_CheckBox_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish - Select/Unselect All.
        /// </summary>
        public static string PublishSelectAll_CheckBox_ToolTip {
            get {
                return ResourceManager.GetString("PublishSelectAll_CheckBox_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String (RESX).
        /// </summary>
        public static string RESX_ComboBoxItem_Content {
            get {
                return ResourceManager.GetString("RESX_ComboBoxItem_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Managed.
        /// </summary>
        public static string ShowManaged_CheckBox_Content {
            get {
                return ResourceManager.GetString("ShowManaged_CheckBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solutions.
        /// </summary>
        public static string Solutions_Button_Content {
            get {
                return ResourceManager.GetString("Solutions_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM/365 Solutions Page.
        /// </summary>
        public static string Solutions_Button_ToolTip {
            get {
                return ResourceManager.GetString("Solutions_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        public static string SolutionsLabel_Label_Content {
            get {
                return ResourceManager.GetString("SolutionsLabel_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vector format (SVG).
        /// </summary>
        public static string SVG_ComboBoxItem_Content {
            get {
                return ResourceManager.GetString("SVG_ComboBoxItem_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crm Dev: Web Resource Deployer.
        /// </summary>
        public static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("Type_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silverlight (XAP).
        /// </summary>
        public static string XAP_ComboBoxItem_Content {
            get {
                return ResourceManager.GetString("XAP_ComboBoxItem_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data (XML).
        /// </summary>
        public static string XML_ComboBoxItem_Content {
            get {
                return ResourceManager.GetString("XML_ComboBoxItem_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style Sheet (XSL).
        /// </summary>
        public static string XSL_ComboBoxItem_Content {
            get {
                return ResourceManager.GetString("XSL_ComboBoxItem_Content", resourceCulture);
            }
        }
    }
}
