//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateWizards.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TemplateWizards.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update D365 DevEx CrmSvcUtil &amp; Solution Packager paths?.
        /// </summary>
        public static string ConfirmMessage_UpdateCrmSvcUtilSolutionPackagerPath {
            get {
                return ResourceManager.GetString("ConfirmMessage_UpdateCrmSvcUtilSolutionPackagerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update D365 DevEx Plug-in Registration Tool path?.
        /// </summary>
        public static string ConfirmMessage_UpdatePrtPath {
            get {
                return ResourceManager.GetString("ConfirmMessage_UpdatePrtPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update user setting.
        /// </summary>
        public static string ConfirmMessage_UpdateUserSetting_Title {
            get {
                return ResourceManager.GetString("ConfirmMessage_UpdateUserSetting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom template.
        /// </summary>
        public static string CustomTemplatePicker_Window_Title {
            get {
                return ResourceManager.GetString("CustomTemplatePicker_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CustomTemplateWindow_Cancel_Button_Tooltip {
            get {
                return ResourceManager.GetString("CustomTemplateWindow_Cancel_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CustomTemplateWindow_Canel_Button_Content {
            get {
                return ResourceManager.GetString("CustomTemplateWindow_Canel_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string CustomTemplateWindow_Ok_Button_Content {
            get {
                return ResourceManager.GetString("CustomTemplateWindow_Ok_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create item from template.
        /// </summary>
        public static string CustomTemplateWindow_Ok_Button_Tooltip {
            get {
                return ResourceManager.GetString("CustomTemplateWindow_Ok_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing template.
        /// </summary>
        public static string ErrorMessage_ErrorProcessingTemplate {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorProcessingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add NuGet package.
        /// </summary>
        public static string ErrorMessage_FailedToAddNuGetPackage {
            get {
                return ResourceManager.GetString("ErrorMessage_FailedToAddNuGetPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemplatePicker had no selected template.
        /// </summary>
        public static string ErrorMessage_NoSelectedTemplate {
            get {
                return ResourceManager.GetString("ErrorMessage_NoSelectedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred running template wizard.
        /// </summary>
        public static string ErrorMessage_TemplateWizardError {
            get {
                return ResourceManager.GetString("ErrorMessage_TemplateWizardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read or deserialize template configuration file.
        /// </summary>
        public static string ErrorMessage_UnableReadDeserializeConfig {
            get {
                return ResourceManager.GetString("ErrorMessage_UnableReadDeserializeConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error.
        /// </summary>
        public static string ErrorMessage_WizardCancelInternalError {
            get {
                return ResourceManager.GetString("ErrorMessage_WizardCancelInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating key.
        /// </summary>
        public static string GeneratingKeyFailureMessage {
            get {
                return ResourceManager.GetString("GeneratingKeyFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Key....
        /// </summary>
        public static string GeneratingKeyStatusBarMessage {
            get {
                return ResourceManager.GetString("GeneratingKeyStatusBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error installing NuGet package.
        /// </summary>
        public static string Message_ErrorInstallingNuGetPackage {
            get {
                return ResourceManager.GetString("Message_ErrorInstallingNuGetPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed NuGet package.
        /// </summary>
        public static string Message_InstalledNuGetPackage {
            get {
                return ResourceManager.GetString("Message_InstalledNuGetPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing NuGet package.
        /// </summary>
        public static string Message_InstallingNuGetPackage {
            get {
                return ResourceManager.GetString("Message_InstallingNuGetPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout installing NuGet package.
        /// </summary>
        public static string Message_TimeoutInstallingNuGetPackage {
            get {
                return ResourceManager.GetString("Message_TimeoutInstallingNuGetPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add custom templates to continue.
        /// </summary>
        public static string MessageBox_AddCustomTemplate {
            get {
                return ResourceManager.GetString("MessageBox_AddCustomTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add template files and try again.
        /// </summary>
        public static string MessageBox_AddTemplateFiles {
            get {
                return ResourceManager.GetString("MessageBox_AddTemplateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create custom template configuration file here?.
        /// </summary>
        public static string MessageBox_CreateConfigFile {
            get {
                return ResourceManager.GetString("MessageBox_CreateConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a template folder under Tools -&gt; Options -&gt; D365 DevEx -&gt; Template Options.
        /// </summary>
        public static string MessageBox_MissingTemplateFolder {
            get {
                return ResourceManager.GetString("MessageBox_MissingTemplateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPM is required to download the XRM type definitions. Install Node.js and the npm package manager. https://nodejs.org.
        /// </summary>
        public static string MessageBox_NPMError {
            get {
                return ResourceManager.GetString("MessageBox_NPMError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string MessageBox_Title_ConfirmCreateConfigFile {
            get {
                return ResourceManager.GetString("MessageBox_Title_ConfirmCreateConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error installing NPM package.
        /// </summary>
        public static string NpmPackageInstallFailureMessage {
            get {
                return ResourceManager.GetString("NpmPackageInstallFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing NPM package.
        /// </summary>
        public static string NpmPackageInstallingStatusBarMessage {
            get {
                return ResourceManager.GetString("NpmPackageInstallingStatusBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NpmPicker_LicenseAccept_TextBlock_Content {
            get {
                return ResourceManager.GetString("NpmPicker_LicenseAccept_TextBlock_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string NpmPickerCancelButtonText {
            get {
                return ResourceManager.GetString("NpmPickerCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string NpmPickerCancelTooltipText {
            get {
                return ResourceManager.GetString("NpmPickerCancelTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string NpmPickerOKButtonText {
            get {
                return ResourceManager.GetString("NpmPickerOKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string NpmPickerOKTooltipText {
            get {
                return ResourceManager.GetString("NpmPickerOKTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error installing NuGet package.
        /// </summary>
        public static string NuGetPackageInstallFailureMessage {
            get {
                return ResourceManager.GetString("NuGetPackageInstallFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing NuGet package.
        /// </summary>
        public static string NuGetPackageInstallingStatusBarMessage {
            get {
                return ResourceManager.GetString("NuGetPackageInstallingStatusBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uninstalling NuGet package.
        /// </summary>
        public static string NuGetPackageUninstallFailureMessage {
            get {
                return ResourceManager.GetString("NuGetPackageUninstallFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling NuGet package.
        /// </summary>
        public static string NuGetPackageUninstallingStatusBarMessage {
            get {
                return ResourceManager.GetString("NuGetPackageUninstallingStatusBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NuGetPicker_LicenseAccept_TextBlock_Content {
            get {
                return ResourceManager.GetString("NuGetPicker_LicenseAccept_TextBlock_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NuGetPicker_LicenseInfoText_TextBlock_Text {
            get {
                return ResourceManager.GetString("NuGetPicker_LicenseInfoText_TextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Versions Only.
        /// </summary>
        public static string NuGetPicker_LimitVersions_CheckBox_Content {
            get {
                return ResourceManager.GetString("NuGetPicker_LimitVersions_CheckBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string NuGetPickerCancelButtonText {
            get {
                return ResourceManager.GetString("NuGetPickerCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string NuGetPickerCancelTooltipText {
            get {
                return ResourceManager.GetString("NuGetPickerCancelTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string NuGetPickerOKButtonText {
            get {
                return ResourceManager.GetString("NuGetPickerOKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string NuGetPickerOKTooltipText {
            get {
                return ResourceManager.GetString("NuGetPickerOKTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.CrmSdk.CoreAssemblies.
        /// </summary>
        public static string SdkAssemblyCore {
            get {
                return ResourceManager.GetString("SdkAssemblyCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.CrmSdk.Extensions.
        /// </summary>
        public static string SdkAssemblyExtensions {
            get {
                return ResourceManager.GetString("SdkAssemblyExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.CrmSdk.Workflow.
        /// </summary>
        public static string SdkAssemblyWorkflow {
            get {
                return ResourceManager.GetString("SdkAssemblyWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.CrmSdk.XrmTooling.CoreAssembly.
        /// </summary>
        public static string SdkAssemblyXrmTooling {
            get {
                return ResourceManager.GetString("SdkAssemblyXrmTooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK accepts any license agreements for this package.
        /// </summary>
        public static string SdkVersionPicker_LicenseAccept_TextBlock_Content {
            get {
                return ResourceManager.GetString("SdkVersionPicker_LicenseAccept_TextBlock_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Info.
        /// </summary>
        public static string SdkVersionPicker_LicenseInfoText_TextBlock_Text {
            get {
                return ResourceManager.GetString("SdkVersionPicker_LicenseInfoText_TextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SdkVersionPickerCancelButtonText {
            get {
                return ResourceManager.GetString("SdkVersionPickerCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SdkVersionPickerCancelTooltipText {
            get {
                return ResourceManager.GetString("SdkVersionPickerCancelTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string SdkVersionPickerOKButtonText {
            get {
                return ResourceManager.GetString("SdkVersionPickerOKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string SdkVersionPickerOKTooltipText {
            get {
                return ResourceManager.GetString("SdkVersionPickerOKTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TestProjectPicker_Cancel_Button_Content {
            get {
                return ResourceManager.GetString("TestProjectPicker_Cancel_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project.
        /// </summary>
        public static string TestProjectPicker_CreateProject_Button_Content {
            get {
                return ResourceManager.GetString("TestProjectPicker_CreateProject_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a unit test project targeting the selected project &amp; the selected unit test framework.
        /// </summary>
        public static string TestProjectPicker_CreateProject_Button_Tooltip {
            get {
                return ResourceManager.GetString("TestProjectPicker_CreateProject_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project To Test.
        /// </summary>
        public static string TestProjectPicker_ProjectToTest_Label_Content {
            get {
                return ResourceManager.GetString("TestProjectPicker_ProjectToTest_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Test Framework.
        /// </summary>
        public static string TestProjectPicker_UnitTestFramework_Label_Content {
            get {
                return ResourceManager.GetString("TestProjectPicker_UnitTestFramework_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit testing framework.
        /// </summary>
        public static string TestProjectPicker_Window_Title {
            get {
                return ResourceManager.GetString("TestProjectPicker_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version_Window_Title {
            get {
                return ResourceManager.GetString("Version_Window_Title", resourceCulture);
            }
        }
    }
}
