//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateWizards.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TemplateWizards.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyKey.snk.
        /// </summary>
        public static string DefaultKeyName {
            get {
                return ResourceManager.GetString("DefaultKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Processing Template: Error Generating Key.
        /// </summary>
        public static string GeneratingKeyFailureMessage {
            get {
                return ResourceManager.GetString("GeneratingKeyFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Key....
        /// </summary>
        public static string GeneratingKeyStatusBarMessage {
            get {
                return ResourceManager.GetString("GeneratingKeyStatusBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Processing Template: Error Installing NuGet Package.
        /// </summary>
        public static string NuGetPackageInstallFailureMessage {
            get {
                return ResourceManager.GetString("NuGetPackageInstallFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing NuGet Package.
        /// </summary>
        public static string NuGetPackageInstallingStatusBarMessage {
            get {
                return ResourceManager.GetString("NuGetPackageInstallingStatusBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.CrmSdk.CoreAssemblies.
        /// </summary>
        public static string SdkAssemblyCore {
            get {
                return ResourceManager.GetString("SdkAssemblyCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.CrmSdk.Extensions.
        /// </summary>
        public static string SdkAssemblyExtensions {
            get {
                return ResourceManager.GetString("SdkAssemblyExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.CrmSdk.Workflow.
        /// </summary>
        public static string SdkAssemblyWorkflow {
            get {
                return ResourceManager.GetString("SdkAssemblyWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.CrmSdk.XrmTooling.CoreAssembly.
        /// </summary>
        public static string SdkAssemblyXrmTooling {
            get {
                return ResourceManager.GetString("SdkAssemblyXrmTooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SdkVersionPickerCancelButtonText {
            get {
                return ResourceManager.GetString("SdkVersionPickerCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SdkVersionPickerCancelTooltipText {
            get {
                return ResourceManager.GetString("SdkVersionPickerCancelTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string SdkVersionPickerOKButtonText {
            get {
                return ResourceManager.GetString("SdkVersionPickerOKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string SdkVersionPickerOKTooltipText {
            get {
                return ResourceManager.GetString("SdkVersionPickerOKTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crm DevEx.
        /// </summary>
        public static string SdkVersionPickerTitle {
            get {
                return ResourceManager.GetString("SdkVersionPickerTitle", resourceCulture);
            }
        }
    }
}
