//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmDeveloperExtensions2.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrmDeveloperExtensions2.Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Menu_Header {
            get {
                return ResourceManager.GetString("About_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK to overwrite file(s)?.
        /// </summary>
        public static string ConfirmMessage_OverwriteFiles {
            get {
                return ResourceManager.GetString("ConfirmMessage_OverwriteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Overwrite.
        /// </summary>
        public static string ConfirmMessage_OverwriteFiles_Title {
            get {
                return ResourceManager.GetString("ConfirmMessage_OverwriteFiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY PROJECT.
        /// </summary>
        public static string Constant_MyProjectFolder {
            get {
                return ResourceManager.GetString("Constant_MyProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string Constant_ProjectBuildConfig_Debug {
            get {
                return ResourceManager.GetString("Constant_ProjectBuildConfig_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string Constant_ProjectBuildConfig_Release {
            get {
                return ResourceManager.GetString("Constant_ProjectBuildConfig_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullPath.
        /// </summary>
        public static string Constant_ProjectProperties_FullPath {
            get {
                return ResourceManager.GetString("Constant_ProjectProperties_FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutputFileName.
        /// </summary>
        public static string Constant_ProjectProperties_OutputFileName {
            get {
                return ResourceManager.GetString("Constant_ProjectProperties_OutputFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutputPath.
        /// </summary>
        public static string Constant_ProjectProperties_OutputPath {
            get {
                return ResourceManager.GetString("Constant_ProjectProperties_OutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROPERTIES.
        /// </summary>
        public static string Constant_PropertiesFolder {
            get {
                return ResourceManager.GetString("Constant_PropertiesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrmSvcUtil Tool Path.
        /// </summary>
        public static string CrmSvcUtilToolPath {
            get {
                return ResourceManager.GetString("CrmSvcUtilToolPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizations.
        /// </summary>
        public static string CustomizationsButton_Customizations_Button_Content {
            get {
                return ResourceManager.GetString("CustomizationsButton_Customizations_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization customizations page.
        /// </summary>
        public static string CustomizationsButton_Customizations_Button_ToolTip {
            get {
                return ResourceManager.GetString("CustomizationsButton_Customizations_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom templates folder.
        /// </summary>
        public static string CustomTemplatesPath {
            get {
                return ResourceManager.GetString("CustomTemplatesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating file from template.
        /// </summary>
        public static string ErrorMessage_CreateFileFromTemplate {
            get {
                return ResourceManager.GetString("ErrorMessage_CreateFileFromTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get directory from string.
        /// </summary>
        public static string ErrorMessage_DirectoryFromString {
            get {
                return ResourceManager.GetString("ErrorMessage_DirectoryFromString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add project reference.
        /// </summary>
        public static string ErrorMessage_ErrorAddProjectReference {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorAddProjectReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last error.
        /// </summary>
        public static string ErrorMessage_ErrorConnecting_LastError {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorConnecting_LastError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last exception.
        /// </summary>
        public static string ErrorMessage_ErrorConnecting_LastException {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorConnecting_LastException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to CRM/365.
        /// </summary>
        public static string ErrorMessage_ErrorCrmConnection {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorCrmConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get path from project.
        /// </summary>
        public static string ErrorMessage_ErrorGetProjectPath {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorGetProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error publishing customizations.
        /// </summary>
        public static string ErrorMessage_ErrorPublishing {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorPublishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error finding extension template directory.
        /// </summary>
        public static string ErrorMessage_FindTemplateDirectory {
            get {
                return ResourceManager.GetString("ErrorMessage_FindTemplateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected to an organization.
        /// </summary>
        public static string ErrorMessage_NotConnectedOrg {
            get {
                return ResourceManager.GetString("ErrorMessage_NotConnectedOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read file from disk.
        /// </summary>
        public static string ErrorMessage_ReadFile {
            get {
                return ResourceManager.GetString("ErrorMessage_ReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error recreating configuration file.
        /// </summary>
        public static string ErrorMessage_RecreateConfigFile {
            get {
                return ResourceManager.GetString("ErrorMessage_RecreateConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read or deserialize configuration file.
        /// </summary>
        public static string ErrorMessage_UnableReadDeserializeConfig {
            get {
                return ResourceManager.GetString("ErrorMessage_UnableReadDeserializeConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to rename file.
        /// </summary>
        public static string ErrorMessage_UnableRenameFile {
            get {
                return ResourceManager.GetString("ErrorMessage_UnableRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing to configuration file.
        /// </summary>
        public static string ErrorMessage_UnableWriteConfig {
            get {
                return ResourceManager.GetString("ErrorMessage_UnableWriteConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing file.
        /// </summary>
        public static string ErrorMessage_WriteFile {
            get {
                return ResourceManager.GetString("ErrorMessage_WriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing temp file.
        /// </summary>
        public static string ErrorMessage_WriteTempFile {
            get {
                return ResourceManager.GetString("ErrorMessage_WriteTempFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Logging Disabled.
        /// </summary>
        public static string ExtensionLoggingDisabled {
            get {
                return ResourceManager.GetString("ExtensionLoggingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Logging Enabled.
        /// </summary>
        public static string ExtensionLoggingEnabled {
            get {
                return ResourceManager.GetString("ExtensionLoggingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to.
        /// </summary>
        public static string HostWindow_SetCaption_ConnectedTo {
            get {
                return ResourceManager.GetString("HostWindow_SetCaption_ConnectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        public static string HostWindow_SetCaption_NotConnected {
            get {
                return ResourceManager.GetString("HostWindow_SetCaption_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string HostWindow_SetCaption_Version {
            get {
                return ResourceManager.GetString("HostWindow_SetCaption_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working.
        /// </summary>
        public static string LockOverlay_LockMessage_Label_DefaultContent {
            get {
                return ResourceManager.GetString("LockOverlay_LockMessage_Label_DefaultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to CRM/365.
        /// </summary>
        public static string Message_SuccessConnecting {
            get {
                return ResourceManager.GetString("Message_SuccessConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to CRM/365 - see Output window for details.
        /// </summary>
        public static string MessageBox_CannotConnect {
            get {
                return ResourceManager.GetString("MessageBox_CannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Status.
        /// </summary>
        public static string MessageBox_CannotConnect_Title {
            get {
                return ResourceManager.GetString("MessageBox_CannotConnect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backed up and recreated configuration file.
        /// </summary>
        public static string MessageBox_RecreatedConfig {
            get {
                return ResourceManager.GetString("MessageBox_RecreatedConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crm DevEx.
        /// </summary>
        public static string OutputLoggerWindowTitle {
            get {
                return ResourceManager.GetString("OutputLoggerWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feel free to make a donation on PayPal.
        /// </summary>
        public static string PayPalButton_OpenPayPal_Button_Tooltip {
            get {
                return ResourceManager.GetString("PayPalButton_OpenPayPal_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug-in Registraion Tool Path.
        /// </summary>
        public static string PluginRegistraionToolPath {
            get {
                return ResourceManager.GetString("PluginRegistraionToolPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out the project on GitHub.
        /// </summary>
        public static string ProjectGitHubButton_OpenGitHub_Button_Tooltip {
            get {
                return ResourceManager.GetString("ProjectGitHubButton_OpenGitHub_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Packager Tool Path.
        /// </summary>
        public static string SolutionPackagerToolPath {
            get {
                return ResourceManager.GetString("SolutionPackagerToolPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solutions.
        /// </summary>
        public static string SolutionsButton_Solutions_Button_Content {
            get {
                return ResourceManager.GetString("SolutionsButton_Solutions_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization solutions page.
        /// </summary>
        public static string SolutionsButton_Solutions_Button_ToolTip {
            get {
                return ResourceManager.GetString("SolutionsButton_Solutions_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out the Spkl project on GitHub.
        /// </summary>
        public static string SpklGitHubButton_OpenGitHub_Button_Tooltip {
            get {
                return ResourceManager.GetString("SpklGitHubButton_OpenGitHub_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string StatusBarMessageConnecting {
            get {
                return ResourceManager.GetString("StatusBarMessageConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intellisense Options.
        /// </summary>
        public static string UserOptions_Category_Intellisense {
            get {
                return ResourceManager.GetString("UserOptions_Category_Intellisense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Options.
        /// </summary>
        public static string UserOptions_Category_Logging {
            get {
                return ResourceManager.GetString("UserOptions_Category_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Options.
        /// </summary>
        public static string UserOptions_Category_Templates {
            get {
                return ResourceManager.GetString("UserOptions_Category_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Tools Options.
        /// </summary>
        public static string UserOptions_Category_Tools {
            get {
                return ResourceManager.GetString("UserOptions_Category_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Browser Options.
        /// </summary>
        public static string UserOptions_Category_WebBrowser {
            get {
                return ResourceManager.GetString("UserOptions_Category_WebBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to latest CrmSvcUtil executable.
        /// </summary>
        public static string UserOptions_Description_CrmSvcToolPath {
            get {
                return ResourceManager.GetString("UserOptions_Description_CrmSvcToolPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed extension logging records extension specific data to a file.
        /// </summary>
        public static string UserOptions_Description_ExtensionLogging {
            get {
                return ResourceManager.GetString("UserOptions_Description_ExtensionLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to extension log file storage.
        /// </summary>
        public static string UserOptions_Description_ExtensionLoggingPath {
            get {
                return ResourceManager.GetString("UserOptions_Description_ExtensionLoggingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get organization metadata and provide string completion - this will require closing and re-opening any files.
        /// </summary>
        public static string UserOptions_Description_Intellisense {
            get {
                return ResourceManager.GetString("UserOptions_Description_Intellisense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the latest Plug-in Registration Tool executable.
        /// </summary>
        public static string UserOptions_Description_RegToolPath {
            get {
                return ResourceManager.GetString("UserOptions_Description_RegToolPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the latest Solution Packager executable.
        /// </summary>
        public static string UserOptions_Description_SolutionPackToolPath {
            get {
                return ResourceManager.GetString("UserOptions_Description_SolutionPackToolPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the folder containing any custom item templates.
        /// </summary>
        public static string UserOptions_Description_TemplatesPath {
            get {
                return ResourceManager.GetString("UserOptions_Description_TemplatesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the internal Visual Studio browser or your default browser for web content.
        /// </summary>
        public static string UserOptions_Description_WebBrowser {
            get {
                return ResourceManager.GetString("UserOptions_Description_WebBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xrm.Tooling logging records organization connect data to a file - this requires reconnecting to the organization.
        /// </summary>
        public static string UserOptions_Description_XrmToolingLogging {
            get {
                return ResourceManager.GetString("UserOptions_Description_XrmToolingLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to Xrm.Tooling log file storage.
        /// </summary>
        public static string UserOptions_Description_XrmToolingLoggingPath {
            get {
                return ResourceManager.GetString("UserOptions_Description_XrmToolingLoggingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrmSvcUtil tool path.
        /// </summary>
        public static string UserOptions_DisplayName_CrmSvcToolPath {
            get {
                return ResourceManager.GetString("UserOptions_DisplayName_CrmSvcToolPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable detailed extension logging?.
        /// </summary>
        public static string UserOptions_DisplayName_ExtensionLogging {
            get {
                return ResourceManager.GetString("UserOptions_DisplayName_ExtensionLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension log file path.
        /// </summary>
        public static string UserOptions_DisplayName_ExtensionLoggingPath {
            get {
                return ResourceManager.GetString("UserOptions_DisplayName_ExtensionLoggingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Intellisense?.
        /// </summary>
        public static string UserOptions_DisplayName_Intellisense {
            get {
                return ResourceManager.GetString("UserOptions_DisplayName_Intellisense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug-in Registration tool path.
        /// </summary>
        public static string UserOptions_DisplayName_RegToolPath {
            get {
                return ResourceManager.GetString("UserOptions_DisplayName_RegToolPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Packager tool path.
        /// </summary>
        public static string UserOptions_DisplayName_SolutionPackToolPath {
            get {
                return ResourceManager.GetString("UserOptions_DisplayName_SolutionPackToolPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to custom templates folder.
        /// </summary>
        public static string UserOptions_DisplayName_TemplatesPath {
            get {
                return ResourceManager.GetString("UserOptions_DisplayName_TemplatesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use internal VS web browser?.
        /// </summary>
        public static string UserOptions_DisplayName_WebBrowser {
            get {
                return ResourceManager.GetString("UserOptions_DisplayName_WebBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Xrm.Tooling logging?.
        /// </summary>
        public static string UserOptions_DisplayName_XrmToolingLogging {
            get {
                return ResourceManager.GetString("UserOptions_DisplayName_XrmToolingLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xrm.Tooling log file path.
        /// </summary>
        public static string UserOptions_DisplayName_XrmToolingLoggingPath {
            get {
                return ResourceManager.GetString("UserOptions_DisplayName_XrmToolingLoggingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intellisense.
        /// </summary>
        public static string UserOptions_Page_Intellisense {
            get {
                return ResourceManager.GetString("UserOptions_Page_Intellisense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string UserOptions_Page_Logging {
            get {
                return ResourceManager.GetString("UserOptions_Page_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string UserOptions_Page_Templates {
            get {
                return ResourceManager.GetString("UserOptions_Page_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Tools.
        /// </summary>
        public static string UserOptions_Page_Tools {
            get {
                return ResourceManager.GetString("UserOptions_Page_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Browser.
        /// </summary>
        public static string UserOptions_Page_WebBrowser {
            get {
                return ResourceManager.GetString("UserOptions_Page_WebBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crm DevEx.
        /// </summary>
        public static string UserOptionsCategory {
            get {
                return ResourceManager.GetString("UserOptionsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &quot;Extension log file path&quot; in user options, logging to output window instead.
        /// </summary>
        public static string WarningMessage_MissingExtensionLogPath {
            get {
                return ResourceManager.GetString("WarningMessage_MissingExtensionLogPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &quot;Xrm.Tooling log file path&quot; in user options, logging to output window instead.
        /// </summary>
        public static string WarningMessage_MissingXrmToolingLogPath {
            get {
                return ResourceManager.GetString("WarningMessage_MissingXrmToolingLogPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-login to last connected organization?.
        /// </summary>
        public static string XrmToolingConnection_AutoLogin_Button_ToolTip {
            get {
                return ResourceManager.GetString("XrmToolingConnection_AutoLogin_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string XrmToolingConnection_Connect_Label_Content {
            get {
                return ResourceManager.GetString("XrmToolingConnection_Connect_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string XrmToolingConnection_Connect_TextBlock_Text {
            get {
                return ResourceManager.GetString("XrmToolingConnection_Connect_TextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect To CRM/D365.
        /// </summary>
        public static string XrmToolingConnection_ConnectImage_Button_Tooltip {
            get {
                return ResourceManager.GetString("XrmToolingConnection_ConnectImage_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string XrmToolingConnection_ProfileList_Label_Content {
            get {
                return ResourceManager.GetString("XrmToolingConnection_ProfileList_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string XrmToolingConnection_SolutionProjectsList_Label_Content {
            get {
                return ResourceManager.GetString("XrmToolingConnection_SolutionProjectsList_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xrm.Tooling Logging Disabled.
        /// </summary>
        public static string XrmToolingLoggingDisabled {
            get {
                return ResourceManager.GetString("XrmToolingLoggingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xrm.Tooling Logging Enabled.
        /// </summary>
        public static string XrmToolingLoggingEnabled {
            get {
                return ResourceManager.GetString("XrmToolingLoggingEnabled", resourceCulture);
            }
        }
    }
}
