//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmDeveloperExtensions2.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrmDeveloperExtensions2.Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-login to last connected org?.
        /// </summary>
        public static string AutoLogin_Button_ToolTip {
            get {
                return ResourceManager.GetString("AutoLogin_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spkl.json.
        /// </summary>
        public static string ConfigFileName {
            get {
                return ResourceManager.GetString("ConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect_TextBlock_Text {
            get {
                return ResourceManager.GetString("Connect_TextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect To CRM/D365.
        /// </summary>
        public static string ConnectImage_Button_Tooltip {
            get {
                return ResourceManager.GetString("ConnectImage_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrmSvcUtil Tool Path.
        /// </summary>
        public static string CrmSvcUtilToolPath {
            get {
                return ResourceManager.GetString("CrmSvcUtilToolPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizations.
        /// </summary>
        public static string Customizations_Button_Content {
            get {
                return ResourceManager.GetString("Customizations_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM/365 Customizations Page.
        /// </summary>
        public static string Customizations_Button_ToolTip {
            get {
                return ResourceManager.GetString("Customizations_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Logging Disabled.
        /// </summary>
        public static string ExtensionLoggingDisabled {
            get {
                return ResourceManager.GetString("ExtensionLoggingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Logging Enabled.
        /// </summary>
        public static string ExtensionLoggingEnabled {
            get {
                return ResourceManager.GetString("ExtensionLoggingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working....
        /// </summary>
        public static string LockMessage_Label_DefaultContent {
            get {
                return ResourceManager.GetString("LockMessage_Label_DefaultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to CRM/365 - see Output window for details.
        /// </summary>
        public static string MessageBox_CannotConnect {
            get {
                return ResourceManager.GetString("MessageBox_CannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Status.
        /// </summary>
        public static string MessageBox_CannotConnect_Title {
            get {
                return ResourceManager.GetString("MessageBox_CannotConnect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to CRM/365: Last error.
        /// </summary>
        public static string OutputLogger_ErrorConnecting_Error {
            get {
                return ResourceManager.GetString("OutputLogger_ErrorConnecting_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last exception.
        /// </summary>
        public static string OutputLogger_ErrorConnecting_Exception {
            get {
                return ResourceManager.GetString("OutputLogger_ErrorConnecting_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to CRM/365.
        /// </summary>
        public static string OutputLogger_SuccessConnecting {
            get {
                return ResourceManager.GetString("OutputLogger_SuccessConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string OutputLoggerMessageTypeError {
            get {
                return ResourceManager.GetString("OutputLoggerMessageTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string OutputLoggerMessageTypeInfo {
            get {
                return ResourceManager.GetString("OutputLoggerMessageTypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string OutputLoggerMessageTypeWarning {
            get {
                return ResourceManager.GetString("OutputLoggerMessageTypeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crm DevEx.
        /// </summary>
        public static string OutputLoggerWindowTitle {
            get {
                return ResourceManager.GetString("OutputLoggerWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug-in Registraion Tool Path.
        /// </summary>
        public static string PluginRegistraionToolPath {
            get {
                return ResourceManager.GetString("PluginRegistraionToolPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project_Label_Content {
            get {
                return ResourceManager.GetString("Project_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Packager Tool Path.
        /// </summary>
        public static string SolutionPackagerToolPath {
            get {
                return ResourceManager.GetString("SolutionPackagerToolPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solutions.
        /// </summary>
        public static string Solutions_Button_Content {
            get {
                return ResourceManager.GetString("Solutions_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM/365 Solutions Page.
        /// </summary>
        public static string Solutions_Button_ToolTip {
            get {
                return ResourceManager.GetString("Solutions_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string StatusBarMessageConnecting {
            get {
                return ResourceManager.GetString("StatusBarMessageConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crm DevEx.
        /// </summary>
        public static string UserOptionsCategory {
            get {
                return ResourceManager.GetString("UserOptionsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intellisense.
        /// </summary>
        public static string UserOptionsIntellisensePage {
            get {
                return ResourceManager.GetString("UserOptionsIntellisensePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intellisense Options.
        /// </summary>
        public static string UserOptionsIntellisensePageCategory {
            get {
                return ResourceManager.GetString("UserOptionsIntellisensePageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string UserOptionsLoggingPage {
            get {
                return ResourceManager.GetString("UserOptionsLoggingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Options.
        /// </summary>
        public static string UserOptionsLoggingPageCategory {
            get {
                return ResourceManager.GetString("UserOptionsLoggingPageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Tools.
        /// </summary>
        public static string UserOptionsToolsPage {
            get {
                return ResourceManager.GetString("UserOptionsToolsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Tools Options.
        /// </summary>
        public static string UserOptionsToolsPageCategory {
            get {
                return ResourceManager.GetString("UserOptionsToolsPageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Browser.
        /// </summary>
        public static string UserOptionsWebBrowserPage {
            get {
                return ResourceManager.GetString("UserOptionsWebBrowserPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Browser Options.
        /// </summary>
        public static string UserOptionsWebBrowserPageCategory {
            get {
                return ResourceManager.GetString("UserOptionsWebBrowserPageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xrm.Tooling Logging Disabled.
        /// </summary>
        public static string XrmToolingLoggingDisabled {
            get {
                return ResourceManager.GetString("XrmToolingLoggingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xrm.Tooling Logging Enabled.
        /// </summary>
        public static string XrmToolingLoggingEnabled {
            get {
                return ResourceManager.GetString("XrmToolingLoggingEnabled", resourceCulture);
            }
        }
    }
}
