//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmDeveloperExtensions.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrmDeveloperExtensions.Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrmDevEx.json.
        /// </summary>
        public static string ConfigFileName {
            get {
                return ResourceManager.GetString("ConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Logging Disabled.
        /// </summary>
        public static string ExtensionLoggingDisabled {
            get {
                return ResourceManager.GetString("ExtensionLoggingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Logging Enabled.
        /// </summary>
        public static string ExtensionLoggingEnabled {
            get {
                return ResourceManager.GetString("ExtensionLoggingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string OutputLoggerMessageTypeError {
            get {
                return ResourceManager.GetString("OutputLoggerMessageTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string OutputLoggerMessageTypeInfo {
            get {
                return ResourceManager.GetString("OutputLoggerMessageTypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string OutputLoggerMessageTypeWarning {
            get {
                return ResourceManager.GetString("OutputLoggerMessageTypeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crm DevEx.
        /// </summary>
        public static string OutputLoggerWindowTitle {
            get {
                return ResourceManager.GetString("OutputLoggerWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string StatusBarMessageConnecting {
            get {
                return ResourceManager.GetString("StatusBarMessageConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crm DevEx.
        /// </summary>
        public static string UserOptionsCategory {
            get {
                return ResourceManager.GetString("UserOptionsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string UserOptionsLoggingPage {
            get {
                return ResourceManager.GetString("UserOptionsLoggingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Options.
        /// </summary>
        public static string UserOptionsLoggingPageCategory {
            get {
                return ResourceManager.GetString("UserOptionsLoggingPageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Browser.
        /// </summary>
        public static string UserOptionsWebBrowserPage {
            get {
                return ResourceManager.GetString("UserOptionsWebBrowserPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Browser Options.
        /// </summary>
        public static string UserOptionsWebBrowserPageCategory {
            get {
                return ResourceManager.GetString("UserOptionsWebBrowserPageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xrm.Tooling Logging Disabled.
        /// </summary>
        public static string XrmToolingLoggingDisabled {
            get {
                return ResourceManager.GetString("XrmToolingLoggingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xrm.Tooling Logging Enabled.
        /// </summary>
        public static string XrmToolingLoggingEnabled {
            get {
                return ResourceManager.GetString("XrmToolingLoggingEnabled", resourceCulture);
            }
        }
    }
}
