//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D365DeveloperExtensions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("D365DeveloperExtensions.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create tool window.
        /// </summary>
        public static string ErrorMessage_CannotCreateToolWindow {
            get {
                return ResourceManager.GetString("ErrorMessage_CannotCreateToolWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing metadata.
        /// </summary>
        public static string Message_ClearingMetadata {
            get {
                return ResourceManager.GetString("Message_ClearingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing CrmLoginForm.
        /// </summary>
        public static string Message_ClosingCrmLoginForm {
            get {
                return ResourceManager.GetString("Message_ClosingCrmLoginForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM Intellisense enabled.
        /// </summary>
        public static string Message_CRMIntellisenseEnabled {
            get {
                return ResourceManager.GetString("Message_CRMIntellisenseEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening CrmLoginForm.
        /// </summary>
        public static string Message_OpeningCrmLoginForm {
            get {
                return ResourceManager.GetString("Message_OpeningCrmLoginForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening tool window.
        /// </summary>
        public static string Message_OpeningToolWindow {
            get {
                return ResourceManager.GetString("Message_OpeningToolWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to CRM?.
        /// </summary>
        public static string MessageBox_ConnectToCrm {
            get {
                return ResourceManager.GetString("MessageBox_ConnectToCrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string MessageBox_ConnectToCrm_Title {
            get {
                return ResourceManager.GetString("MessageBox_ConnectToCrm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing extension.
        /// </summary>
        public static string TraceInfo_InitializingExtension {
            get {
                return ResourceManager.GetString("TraceInfo_InitializingExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing menu.
        /// </summary>
        public static string TraceInfo_InitializingMenu {
            get {
                return ResourceManager.GetString("TraceInfo_InitializingMenu", resourceCulture);
            }
        }
    }
}
