//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluginTraceViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PluginTraceViewer.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlation Id.
        /// </summary>
        public static string CorrelationId_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("CorrelationId_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string CreatonOn_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("CreatonOn_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Logs.
        /// </summary>
        public static string DeleteLogsImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("DeleteLogsImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth.
        /// </summary>
        public static string Depth_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("Depth_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        public static string Entity_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("Entity_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Duration.
        /// </summary>
        public static string ExecutionDuration_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("ExecutionDuration_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("Message_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("Mode_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open In CRM/365.
        /// </summary>
        public static string OpenInCrmImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("OpenInCrmImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Polling.
        /// </summary>
        public static string Poll_Button_Content {
            get {
                return ResourceManager.GetString("Poll_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start polling CRM/365 for new plug-in trace logs.
        /// </summary>
        public static string Poll_Button_ToolTip {
            get {
                return ResourceManager.GetString("Poll_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Polling.
        /// </summary>
        public static string PollOff_Button_Content {
            get {
                return ResourceManager.GetString("PollOff_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop polling CRM/365 for plug-in trace logs.
        /// </summary>
        public static string PollOff_Button_ToolTip {
            get {
                return ResourceManager.GetString("PollOff_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("RefreshImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crm Dev: Plug-in Trace Viewer.
        /// </summary>
        public static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        public static string TypeName_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("TypeName_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string ViewDetailsImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("ViewDetailsImage_Button_ToolTip", resourceCulture);
            }
        }
    }
}
