//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluginTraceViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PluginTraceViewer.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting plug-in trace log.
        /// </summary>
        public static string ErrorMessage_ErrorDeletingTrace {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorDeletingTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting plug-in trace logs.
        /// </summary>
        public static string ErrorMessage_ErrorDeletingTraces {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorDeletingTraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving plug-in trace logs.
        /// </summary>
        public static string ErrorMessage_ErrorRetrievingTraces {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorRetrievingTraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string FilterEntity_Select_All {
            get {
                return ResourceManager.GetString("FilterEntity_Select_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new traces.
        /// </summary>
        public static string Info_NoNewTraces {
            get {
                return ResourceManager.GetString("Info_NoNewTraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieved new traces.
        /// </summary>
        public static string Info_RetrievedNewTraces {
            get {
                return ResourceManager.GetString("Info_RetrievedNewTraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusting next poll time to.
        /// </summary>
        public static string Message_AdjustingNextPollTo {
            get {
                return ResourceManager.GetString("Message_AdjustingNextPollTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted plug-in trace log.
        /// </summary>
        public static string Message_DeletedTraceLog {
            get {
                return ResourceManager.GetString("Message_DeletedTraceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting plug-in trace logs.
        /// </summary>
        public static string Message_DeletingTraces {
            get {
                return ResourceManager.GetString("Message_DeletingTraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last plug-in trace log created time.
        /// </summary>
        public static string Message_LastLogCreatedTime {
            get {
                return ResourceManager.GetString("Message_LastLogCreatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving plug-in traces.
        /// </summary>
        public static string Message_RetrievingTraces {
            get {
                return ResourceManager.GetString("Message_RetrievingTraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next poll in.
        /// </summary>
        public static string PluginTraceViewer_PollTime_Label_Content {
            get {
                return ResourceManager.GetString("PluginTraceViewer_PollTime_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlation Id.
        /// </summary>
        public static string PluginTraceViewerWindow_CorrelationId_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("PluginTraceViewerWindow_CorrelationId_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string PluginTraceViewerWindow_CreatonOn_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("PluginTraceViewerWindow_CreatonOn_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Logs.
        /// </summary>
        public static string PluginTraceViewerWindow_DeleteLogsImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("PluginTraceViewerWindow_DeleteLogsImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth.
        /// </summary>
        public static string PluginTraceViewerWindow_Depth_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("PluginTraceViewerWindow_Depth_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search trace logs.
        /// </summary>
        public static string PluginTraceViewerWindow_DetailsSearch_TextBlock_Text {
            get {
                return ResourceManager.GetString("PluginTraceViewerWindow_DetailsSearch_TextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        public static string PluginTraceViewerWindow_Entity_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("PluginTraceViewerWindow_Entity_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Duration.
        /// </summary>
        public static string PluginTraceViewerWindow_ExecutionDuration_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("PluginTraceViewerWindow_ExecutionDuration_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped polling for plug-in trace log records.
        /// </summary>
        public static string PluginTraceViewerWindow_Info_StoppedPolling {
            get {
                return ResourceManager.GetString("PluginTraceViewerWindow_Info_StoppedPolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string PluginTraceViewerWindow_Message_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("PluginTraceViewerWindow_Message_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving plug-in trace logs.
        /// </summary>
        public static string PluginTraceViewerWindow_Message_GettingTraces {
            get {
                return ResourceManager.GetString("PluginTraceViewerWindow_Message_GettingTraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string PluginTraceViewerWindow_Mode_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("PluginTraceViewerWindow_Mode_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in CRM/365.
        /// </summary>
        public static string PluginTraceViewerWindow_OpenInCrmImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("PluginTraceViewerWindow_OpenInCrmImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Polling.
        /// </summary>
        public static string PluginTraceViewerWindow_Poll_Button_Content {
            get {
                return ResourceManager.GetString("PluginTraceViewerWindow_Poll_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start polling for new plug-in trace logs.
        /// </summary>
        public static string PluginTraceViewerWindow_Poll_Button_ToolTip {
            get {
                return ResourceManager.GetString("PluginTraceViewerWindow_Poll_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Polling.
        /// </summary>
        public static string PluginTraceViewerWindow_PollOff_Button_Content {
            get {
                return ResourceManager.GetString("PluginTraceViewerWindow_PollOff_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop polling for plug-in trace logs.
        /// </summary>
        public static string PluginTraceViewerWindow_PollOff_Button_ToolTip {
            get {
                return ResourceManager.GetString("PluginTraceViewerWindow_PollOff_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh logs.
        /// </summary>
        public static string PluginTraceViewerWindow_RefreshImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("PluginTraceViewerWindow_RefreshImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started polling for plug-in trace log records: Interval 30 seconds.
        /// </summary>
        public static string PluginTraceViewerWindow_StartedPolling {
            get {
                return ResourceManager.GetString("PluginTraceViewerWindow_StartedPolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        public static string PluginTraceViewerWindow_TypeName_DataGridTextColumn_Header {
            get {
                return ResourceManager.GetString("PluginTraceViewerWindow_TypeName_DataGridTextColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        public static string PluginTraceViewerWindow_ViewDetailsImage_Button_ToolTip {
            get {
                return ResourceManager.GetString("PluginTraceViewerWindow_ViewDetailsImage_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D365 DevEx: Plug-in Trace Viewer.
        /// </summary>
        public static string PluginTraceViewerWindow_Window_Title {
            get {
                return ResourceManager.GetString("PluginTraceViewerWindow_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search trace details.
        /// </summary>
        public static string PluginTraceViewWindow_DetailsSearch_TextBlock_Text {
            get {
                return ResourceManager.GetString("PluginTraceViewWindow_DetailsSearch_TextBlock_Text", resourceCulture);
            }
        }
    }
}
